"use client";

import React from "react";

export default function UiOverlay() {
  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        pointerEvents: "none",
        zIndex: 50,
        display: "flex",
        alignItems: "flex-start",
        justifyContent: "flex-start",
        padding: 44,
        boxSizing: "border-box",
        fontFamily: '"CircularStd", system-ui, -apple-system, Arial, sans-serif',
        fontWeight: 400, // Book
      }}
    >
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
          justifyContent: "space-between",
          gap: 10,
        }}
      >
        {/* Header (top-left) */}
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "40px 1fr",
            columnGap: 12,
            rowGap: 10,
            alignItems: "start",
          }}
        >
          {/* logo */}
          <img
            src="/img/logo_w.png"
            alt="logo"
            style={{
              width: 40,
              height: 40,
              display: "block",
            }}
          />

          {/* name (row 1, col 2) */}
          <div
            style={{
              color: "white",
              fontWeight: 400,
              fontSize: 28,
              lineHeight: 1.2,
              paddingTop: 2, // 로고와 베이스라인 미세 정렬
            }}
          >
            Seong Julee
          </div>

          {/* description (row 2, col 2) - 이름 아래에 정렬 */}
          <div
            style={{
              gridColumn: "2 / 3",
              color: "white",
              opacity: 0.9,
              maxWidth: 420,
              fontWeight: 400,
              fontSize: 16,
              lineHeight: 1.35,
            }}
          >
            My work bridges research, strategy and storytelling to design
            emotionally meaningful experiences for people
          </div>
        </div>

        {/* Center: 6 images (vertical stack, nowrap, fixed sizes) */}
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            flexWrap: "nowrap",
            gap: 10,
            pointerEvents: "none",
          }}
        >
          <img
            src="/img/intro_text_01.png"
            alt="intro 01"
            style={{ width: 401, height: 42.2, display: "block" }}
          />
          <img
            src="/img/intro_text_02.png"
            alt="intro 02"
            style={{ width: 312.7, height: 30.4, display: "block" }}
          />
          <img
            src="/img/intro_text_03.png"
            alt="intro 03"
            style={{ width: 484.6, height: 38.9, display: "block" }}
          />
          <img
            src="/img/intro_text_04.png"
            alt="intro 04"
            style={{ width: 414.5, height: 30.6, display: "block" }}
          />
          <img
            src="/img/intro_text_05.png"
            alt="intro 05"
            style={{ width: 352.4, height: 31.4, display: "block" }}
          />
          <img
            src="/img/intro_text_06.png"
            alt="intro 06"
            style={{ width: 238.7, height: 38.8, display: "block" }}
          />
        </div>

        {/* Footer (bottom-left) */}
        <div
          style={{
            color: "rgba(255,255,255,0.35)",
            fontWeight: 400,
            fontSize: 12,
            lineHeight: 1.5,
            maxWidth: 520,
          }}
        >
          <div>This website was built with code generated by Claude.</div>
          <div>
            Before 2010, I worked as a Senior Designer at d’strict Creative Lab
            and as a Senior Designer at Tangram Design Factory.
          </div>
        </div>
      </div>
    </div>
  );
}
